### ISSUE TITLE
Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.

### ISSUE THREAD

**Issue by mark342703702** [agrass-GitHub/element-plus-crx#1]
slot: () => <div>操作</div>  这种写法会报错

报错信息：Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.

项目中引用了 @vitejs/plugin-vue ，还是会报错

**Comment by agrass-GitHub** [comment]
给项目添加 jsx 支持
