### ISSUE TITLE
Internal server error: [@vue/compiler-sfc] Failed to resolve extends base type.

### ISSUE THREAD

**Issue by seamusic** [agrass-GitHub/element-plus-crx#11]
确认是完全按照快速开始的要求使用方式进行，vue为3.5，但集成使用时报错：

`23:33:50 [vite] Internal server error: [@vue/compiler-sfc] Failed to resolve extends base type.
If this previously worked in 3.2, you can instruct the compiler to ignore this extend by adding /* @vue-ignore */ before it, for example:

interface Props extends /* @vue-ignore */ Base {}

Note: both in 3.2 or with the ignore, the properties in the base type are treated as fallthrough attrs at runtime.

anonymous.vue
46 |  import type { ColumnProps, TableEmits, MergeProps, PageProps, SortParams } from './type'
47 |
48 |  interface Props extends Omit<TableProps<any>, 'default-sort'>, TableEmits<any> {
   |                                                                 ^^^^^^^^^^^^^^^
49 |    columns?: ColumnProps[]
50 |    page?: PageProps
  Plugin: vite:setup-name-support`

![image](https://github.com/user-attachments/assets/160e0c57-2779-4f4f-85e4-7a21bf6bfd6e)

**Comment by agrass-GitHub** [comment]
麻烦给出完整的 package.json，或者 viteconfig.js 也截图贴下

**Comment by agrass-GitHub** [comment]
我新建最新版本的vue，3.4 没什么问题。
```
{
  "name": "vue-project",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "element-plus": "^2.8.4",
    "element-plus-crx": "^1.1.6",
    "typescript": "^5.6.2",
    "vue": "^3.4.29"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.5",
    "@vitejs/plugin-vue-jsx": "^4.0.0",
    "vite": "^5.3.1"
  }
}
```
