### ISSUE TITLE
描述列表，没有herder的时候，也生成了heder div。

### ISSUE THREAD

**Issue by sosovia** [agrass-GitHub/element-plus-crx#13]
描述列表，没有herder的时候，也生成了heder div。虽然高度为0。但实际还是有那个占位的。跟select的内容缩进类似的。
![02cd56b8470d7d38b1bfa07b222ba67](https://github.com/user-attachments/assets/82d6f73b-15b4-4530-90d9-b17913b544b9)
![6211181eafe37c71f9d8511366b3f78](https://github.com/user-attachments/assets/34cd103f-b087-43ce-af0c-6c78db0458d1)

**Comment by agrass-GitHub** [comment]
已更新
