### ISSUE TITLE
关于使用文档的两个问题

### ISSUE THREAD

**Issue by lastonesky** [agrass-GitHub/element-plus-crx#6]
1.Gitee的连接似乎挂了，打不开了。
2.Github 使用文档，一旦点击了Navigation 导航下面的Menu或者ContextMenu，再点其他的就没有用了，比如说再点左侧Table的说明，右侧虽然定位了，但是内容还是刚才的Menu或者ContextMenu的内容。

**Comment by agrass-GitHub** [comment]
收到，这两天看看

**Comment by agrass-GitHub** [comment]
1. 码云的 page 服务下架了
