### ISSUE TITLE
【优化建议】插槽内嵌套的组件事件无响应

### ISSUE THREAD

**Issue by CrazyStudent13** [agrass-GitHub/element-plus-crx#8]
![image](https://github.com/user-attachments/assets/399b5d58-f5c1-42b2-b3be-c09a92068cda)
我封装了一个下拉框，使用form的插槽写法，change事件无响应，而放在外侧就可以使用。
虽然可以通过其他方式规避，但是还是希望能优化掉这个怪毛病

**Comment by agrass-GitHub** [comment]
emm，把你的组件代码，贴上来呢。颗粒度越细越好，方便我复现。

**Comment by agrass-GitHub** [comment]
`
<template>
  <ElForm label-width="80px" :model="form.model" class="demo">
    <AgelFormGrid :items="form.items" :span="8" :gutter="10">
      <template #slot-input>
        <ElInput v-model="form.model.sex" placeholder="请输入123" @change="inputChange" />
      </template>
    </AgelFormGrid>
  </ElForm>
</template>

<script setup>
import { reactive } from 'vue'
const form = reactive({
  model: {
    sex: ''
  },
  items: [
    { prop: 'name', label: '姓名' },
    { prop: 'sex', label: '性别', slot: 'slot-input' },
    { prop: 'intor', label: '介绍' },
    { prop: 'address', label: '地址', span: 24 }
  ]
})

function inputChange(v) {
  console.log(v)
}
`
![image](https://github.com/user-attachments/assets/d97aad26-fe02-4aaa-ba59-a3818a45d752)

我这边测试都是可以正常触发的，建议看看依赖是否最新，再你看看你的组件问题吧。

**Comment by CrazyStudent13** [comment]
`<template>
  <el-select v-bind="$attrs" class="w-[160px]" filterable @change="handleChange">
    <el-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value" />
  </el-select>
</template>

<script lang="ts" setup>
import request from '~/src/utils/request'
import { useCallTableStore } from '/@/store/modules/callTable'

type ModuleType = {
  id: number
  moduleName: string
  moduleNo: string
}
type Option = { label: string; value: number | string; code?: string }
// 平台调用表组件
defineOptions({
  name: 'CallTable',
})

const emit = defineEmits(['change', 'changeRow', 'chooseLabel', 'defalltSelect'])

const currentAttr = useAttrs()
const callTableStore = useCallTableStore()
const callTableData = computed(() => callTableStore.callTableData)
const options = ref<{ label: string; value: number | string }[]>([])
const selectData = ref<any[]>([])

// 处理change事件的返回值
const handleChange = (val: number | string) => {
  console.log(val)
  // 多选时返回数组 单选时返回对象或值
  if (currentAttr.multiple && Array.isArray(val) && val.length > 0) {
    const backValue: Option[] = options.value.reduce((acc: Option[], { value, label, code }: Option) => {
      if (val.includes(value)) {
        acc.push({ value, label, code })
      }
      return acc
    }, [])
    emit('change', backValue)
  } else {
    // 返回选中的value与label
    const valObj = options.value.find(({ value }) => value === val)
    console.log(valObj, '!!!')
    emit('change', valObj?.value, valObj?.label)
    emit('chooseLabel', valObj)
    // 返回选中列的所有数据
    const transferData = currentBindTableName.value
    const row = selectData.value.find((item: any) => item[transferData!.value] === val)
    emit('changeRow', row)
  }
}

const getCallTableSelect = async () => {
  let queryUrl = currentBindTableName.value?.url
  // 截取currentBindTableName.value?.url第一个字符 判断是不是‘/’
  if (queryUrl?.charAt(0) === '/') {
    queryUrl = queryUrl.slice(1)
  }
  const res = await request<ModuleType[], ModuleType[]>({
    url: `/${queryUrl}`,
    method: 'get',
    params: {
      tableName: currentAttr['table-name'],
      str: currentAttr['type-no'],
    },
  })
  selectData.value = res
  options.value = res.map((item: any) => {
    const transferData = currentBindTableName.value
    if (transferData?.['no']) {
      return {
        label: `${item[transferData?.label]}(${item[transferData?.no]})`,
        code: item[transferData?.label],
        value: item[transferData?.value],
      }
    } else {
      return {
        label: item[transferData!.label],
        value: item[transferData!.value],
      }
    }
  })
  emit('defalltSelect', options.value)
}

onMounted(async () => {
  getCallTableSelect()
})

const currentBindTableName = computed(() => {
  const tableName = currentAttr['table-name']
  return callTableData.value.find((item) => {
    return item.tableNo === tableName
  })
})

const reload = () => {
  getCallTableSelect()
}

defineExpose({
  reload,
})
</script>
`
这个组件就是处理数据字典的，您这边可以简化一下，大概就可以复现

**Comment by CrazyStudent13** [comment]
```
<template>
  <el-select v-bind="$attrs" filterable @change="handleChange">
    <el-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value" />
  </el-select>
</template>

<script lang="ts" setup>
// 处理change事件的返回值
const handleChange = (val: number | string) => {
  console.log(val)
  // 多选时返回数组 单选时返回对象或值
  if (currentAttr.multiple && Array.isArray(val) && val.length > 0) {
    const backValue: Option[] = options.value.reduce((acc: Option[], { value, label, code }: Option) => {
      if (val.includes(value)) {
        acc.push({ value, label, code })
      }
      return acc
    }, [])
    emit('change', backValue)
  } else {
    // 返回选中的value与label
    const valObj = options.value.find(({ value }) => value === val)
    console.log(valObj, '!!!')
    emit('change', valObj?.value, valObj?.label)
    emit('chooseLabel', valObj)
    // 返回选中列的所有数据
    const transferData = currentBindTableName.value
    const row = selectData.value.find((item: any) => item[transferData!.value] === val)
    emit('changeRow', row)
  }
}
</script>
```

您好，我这边大概简化了一下，就是我自己封装的下拉选项框，作为组件引入之后，会出现的问题。

我将最核心的逻辑放出来了，您看看能否复现呢？

**Comment by agrass-GitHub** [comment]
肉眼来看，如果 change 事件没有触发，很明显就是 第一个 if 没有走进去，没有触发  emit('change', backValue)，而是触发的  emit('changeRow', row)。

你同时监听两个事件就应该会触发其中之一。

**Comment by CrazyStudent13** [comment]
> 肉眼来看，如果 change 事件没有触发，很明显就是 第一个 if 没有走进去，没有触发 emit('change', backValue)，而是触发的 emit('changeRow', row)。
> 
> 你同时监听两个事件就应该会触发其中之一。

要不您稍等，午休时候 我尝试将那个问题复现一下，到时候我贴一下结果，我印象中是if的判断是走进去了，但是change的回传事件没有触发。

**Comment by CrazyStudent13** [comment]
> > 肉眼来看，如果 change 事件没有触发，很明显就是 第一个 if 没有走进去，没有触发 emit('change', backValue)，而是触发的 emit('changeRow', row)。
> > 你同时监听两个事件就应该会触发其中之一。
> 
> 要不您稍等，午休时候 我尝试将那个问题复现一下，到时候我贴一下结果，我印象中是if的判断是走进去了，但是change的回传事件没有触发。

不知为何，又无法复现了，但是我确实记得上次这里没法使用，当时我还调了好一阵子，今天重新试了一下又可以了，emmm....我的问题，不好意思，耽误大佬的时间了。
