### ISSUE TITLE
都报 [@vue/compiler-sfc] Failed to resolve extends base type.这个错，用不了

### ISSUE THREAD

**Issue by xlstyle** [agrass-GitHub/element-plus-crx#9]
[plugin:vite:setup-name-support] [@vue/compiler-sfc] Failed to resolve extends base type.
If this previously worked in 3.2, you can instruct the compiler to ignore this extend by adding /* @vue-ignore */ before it, for example:

interface Props extends /* @vue-ignore */ Base {}

Note: both in 3.2 or with the ignore, the properties in the base type are treated as fallthrough attrs at runtime.

anonymous.vue
29 |  >
30 |  
31 |  interface Props extends Partial<TooltipProps> {
   |                          ^^^^^^^^^^^^^^^^^^^^^
32 |    lineClamp?: number
33 |    wordClamp?: number

**Comment by agrass-GitHub** [comment]
![image](https://github.com/user-attachments/assets/9b888e6f-d11f-4f65-a14e-5b36e9c07d60)

**Comment by agrass-GitHub** [comment]
不能使用：vite-plugin-vue-setup-extend
